package com.wentuyi.app

import android.content.Context
import java.io.BufferedReader
import java.io.InputStreamReader

/**
 * The IME's pinyin dictionary, backed by `assets/pinyin.txt`.
 *
 * Replaces the hand-written 435-entry table this file's predecessor shipped. That table
 * carried 1–3 characters per syllable, and the *right* character usually wasn't among
 * them — 今 was missing under `jin`, 北 under `bei`, 问 under `wen` — so `wojintian`
 * came out as 我进天 with no second candidate to pick instead. The keyboard could not be
 * used to type Chinese, which is the one thing a Chinese keyboard has to do.
 *
 * The table is generated by `scripts/gen-pinyin-table.py` from pypinyin + jieba data
 * (both MIT) and committed, so neither the build nor CI needs Python:
 *  - **416 syllables** (all of Mandarin) with up to 24 characters each, ranked by corpus
 *    frequency so 是/时/使/事 lead `shi` instead of trailing a dozen rare homophones.
 *  - **~41k words** keyed by their concatenated toneless pinyin, ranked by corpus
 *    frequency, so `jintian`, `mingtian`, `xianzai` resolve as whole words.
 *  - a 0–15 log2 frequency bucket per entry, which is what lets the runtime rank across
 *    keys — both for prefix matches and for scoring competing segmentations.
 *
 * Lookup order matches what a user expects while typing incrementally:
 *  1. exact word match on everything typed so far (`beijing` → 北京),
 *  2. words that *start* with what's typed (`bei` → 北京, 备份…), so candidates appear
 *     before the syllable is finished,
 *  3. single characters for the typed syllable,
 *  4. a whole-buffer segmentation for long inputs (`wojintianyaochuqu`).
 *
 * Loading parses ~700 KB, so [load] must run off the main thread; until it finishes
 * [isReady] is false and [candidatesFor] returns empty rather than blocking the keyboard.
 */
object PinyinEngine {
    private const val ASSET = "pinyin.txt"
    private const val MAX_CANDIDATES = 24

    /** Longest piece [segment] will consider: a 4-character word can run ~24 letters. */
    private const val MAX_PIECE_LEN = 24

    /**
     * Fixed score charged per segmentation piece. Total input length is constant across
     * every candidate split, so a per-character length bonus cancels out entirely and does
     * nothing; what actually decides the split is how many pieces it takes. Without this
     * penalty the DP shatters `mingtian` into 米+嗯+体+啊+嗯, because five common single
     * characters out-score one common word. 20 is tuned so a word beats its own
     * character-by-character split, and beats a garbage split by a wide margin.
     */
    private const val PIECE_COST = 20

    /** Value strings are "<bucket hex><payload>"; entry() splits them without a second map. */
    @Volatile private var singles: Map<String, String> = emptyMap()
    @Volatile private var words: Map<String, String> = emptyMap()
    /** Sorted word keys, for binary-searching the prefix range without scanning 33k keys. */
    @Volatile private var wordKeys: Array<String> = emptyArray()
    @Volatile private var ready = false

    val isReady: Boolean get() = ready

    /** Parses the asset. Blocking and allocation-heavy — call from a background thread. */
    @Synchronized
    fun load(context: Context) {
        if (ready) return
        val s = HashMap<String, String>(600)
        val w = HashMap<String, String>(40_000)
        try {
            context.applicationContext.assets.open(ASSET).use { stream ->
                BufferedReader(InputStreamReader(stream, Charsets.UTF_8), 32 * 1024)
                    .forEachLine { line ->
                        // S<TAB>key<TAB>bucket<TAB>chars   |   W<TAB>key<TAB>bucket<TAB>words
                        if (line.isEmpty() || line[0] == '#') return@forEachLine
                        val a = line.indexOf('\t')
                        if (a <= 0) return@forEachLine
                        val b = line.indexOf('\t', a + 1)
                        if (b <= a) return@forEachLine
                        val c = line.indexOf('\t', b + 1)
                        if (c <= b) return@forEachLine
                        val key = line.substring(a + 1, b)
                        val value = line.substring(b + 1, c) + line.substring(c + 1)
                        when (line[0]) {
                            'S' -> s[key] = value
                            'W' -> w[key] = value
                        }
                    }
            }
        } catch (e: Exception) {
            // A missing/corrupt asset must degrade to "no candidates", never crash the IME —
            // the user can still commit raw pinyin and every non-Chinese path keeps working.
            return
        }
        singles = s
        words = w
        wordKeys = w.keys.toTypedArray().also { it.sort() }
        ready = true
    }

    /** Best-effort single result for "commit whatever the first candidate is". */
    fun firstCandidateOrRaw(input: String): String =
        candidatesFor(input).firstOrNull() ?: normalize(input)

    fun candidatesFor(input: String): List<String> {
        val key = normalize(input)
        if (key.isEmpty() || !ready) return emptyList()
        val out = ArrayList<String>(MAX_CANDIDATES)

        // 1. The whole buffer is a word — 你好 must lead at "nihao".
        words[key]?.let { for (word in payload(it).split(' ')) addUnique(out, word) }

        // 2. Single characters for this exact syllable. Ahead of prefix words on purpose:
        //    at "wo" the user overwhelmingly wants 我, not 卧铺.
        singles[key]?.let { for (ch in payload(it)) addUnique(out, ch.toString()) }

        // 3. Words the buffer is a prefix of, so 北京 appears while typing "beij".
        //    Skipped for long buffers, where an exact match or a segmentation is the intent.
        if (out.size < MAX_CANDIDATES && key.length <= 10) {
            for (candidate in prefixMatches(key, MAX_CANDIDATES - out.size)) {
                addUnique(out, candidate)
            }
        }

        // 4. Segment the whole buffer, for sentence-length input.
        if (key.length > 1) segment(key)?.let { addUnique(out, it) }

        return out
    }

    private fun bucket(value: String): Int = Character.digit(value[0], 16)

    private fun payload(value: String): String = value.substring(1)

    /**
     * Words whose key starts with [prefix], best-ranked first. [wordKeys] is sorted, so the
     * matching keys form one contiguous range found by binary search — a linear scan over
     * 33k keys on every keystroke would be visible as lag.
     */
    private fun prefixMatches(prefix: String, limit: Int): List<String> {
        val keys = wordKeys
        if (keys.isEmpty() || limit <= 0) return emptyList()
        var lo = 0
        var hi = keys.size
        while (lo < hi) {
            val mid = (lo + hi) ushr 1
            if (keys[mid] < prefix) lo = mid + 1 else hi = mid
        }
        val out = ArrayList<String>(limit)
        var i = lo
        val range = ArrayList<String>(48)
        while (i < keys.size && keys[i].startsWith(prefix) && range.size < 48) {
            range += keys[i]; i++
        }
        // Most frequent first, then shortest: at "bei", 北京 must beat 北京大学 and 卑鄙.
        range.sortWith(compareByDescending<String> { words[it]?.let(::bucket) ?: 0 }
            .thenBy { it.length })
        for (k in range) {
            for (word in payload(words[k] ?: continue).split(' ')) {
                if (out.size >= limit) return out
                out += word
            }
        }
        return out
    }

    /**
     * Best-scoring segmentation of the whole buffer, by dynamic programming over every
     * split rather than greedy longest-match. Greedy was what turned `wojintianyaochuqu`
     * into 我进天要出去: it grabbed the longest matching prefix regardless of how bad the
     * remainder became. The DP maximises the summed piece score, where each piece pays
     * [PIECE_COST], so a real word beats both its own character-by-character split and any
     * shredding into stray syllables.
     *
     * One result only — this is the "you typed a whole sentence" fallback, not a
     * replacement for picking candidates syllable by syllable.
     */
    private fun segment(input: String): String? {
        val n = input.length
        val neg = Int.MIN_VALUE / 4
        val score = IntArray(n + 1) { neg }
        val next = IntArray(n + 1) { -1 }
        score[n] = 0
        for (start in n - 1 downTo 0) {
            val maxEnd = minOf(n, start + MAX_PIECE_LEN)
            for (end in maxEnd downTo start + 1) {
                if (score[end] == neg) continue
                val piece = input.substring(start, end)
                val entry = words[piece] ?: singles[piece] ?: continue
                val total = bucket(entry) - PIECE_COST + score[end]
                if (total > score[start]) {
                    score[start] = total
                    next[start] = end
                }
            }
        }
        if (score[0] == neg) return null
        val sb = StringBuilder(n / 2 + 1)
        var i = 0
        while (i < n) {
            val end = next[i]
            if (end <= i) return null
            val piece = input.substring(i, end)
            val word = words[piece]
            if (word != null) sb.append(payload(word).substringBefore(' '))
            else sb.append(payload(singles[piece] ?: return null)[0])
            i = end
        }
        return sb.toString().takeIf { it.isNotEmpty() }
    }

    private fun addUnique(out: ArrayList<String>, candidate: String) {
        if (out.size < MAX_CANDIDATES && candidate.isNotEmpty() && !out.contains(candidate)) {
            out += candidate
        }
    }

    /** 'V'/'Ü' are how people type ü on a Latin keyboard; the table is keyed on 'v'. */
    private fun normalize(input: String): String {
        val sb = StringBuilder(input.length)
        for (c in input) {
            when {
                c in 'a'..'z' -> sb.append(c)
                c in 'A'..'Z' -> sb.append(c + 32)
                c == 'ü' || c == 'Ü' -> sb.append('v')
            }
        }
        return sb.toString()
    }
}
